project: dataset-allele
program: models_scripts/v1_mha/train-server2-bb-task_dropout_sweep.py
method: bayes  # oder "random" für schnelleres explorieren

metric:
  name: val_ap
  goal: maximize

parameters:
  learning_rate:
    min: 0.00001
    max: 0.001
  weight_decay:
    min: 0.00001
    max: 0.01
  batch_size:
    values: [64, 128, 256]
  num_layers:
    values: [1, 2]
  num_heads:
    values: [1, 2]
  optimizer:
    values: ["adam"]
  attn_dropout:
    min: 0.2
    max: 0.5
  ffn_dropout:
    min: 0.2
    max: 0.5
  res_dropout:
    min: 0.2
    max: 0.5
  classifier_hidden_dim:
    values: [64, 128, 256]