epochs: 35
batch_size: 32
learning_rate: 0.001
embed_dim: 128
num_heads: 8
num_layers: 2
max_tcr_length: 43
max_epitope_length: 43
model_path: "results/trained_models/v1_mha/v1_mha_multimodal.pth"
ple_embeddings: "../../data/physico/ple_encoded_physchem.h5"
descriptor_embeddings: "../../data/physico/descriptor_encoded_physchem.h5"
data_paths:
  train: "../../../../data/splitted_datasets/allele/beta/train.tsv"
  val: "../../../../data/splitted_datasets/allele/beta/validation.tsv"
  test: "../../../../data/splitted_datasets/allele/beta/test.tsv"
embeddings:
  tcr: "../../data/embeddings/beta/allele/padded/padded_tcr_embeddings_final.h5"
  epitope: "../../data/embeddings/beta/allele/padded/padded_epitope_embeddings_final.h5"
  tcr_train: "../../data/embeddings/beta/allele/dimension_1024/padded_train_tcr_embeddings_final.h5"
  epitope_train: "../../data/embeddings/beta/allele/dimension_1024/padded_train_epitope_embeddings_final.h5"
  tcr_valid: "../../data/embeddings/beta/allele/dimension_1024/padded_valid_tcr_embeddings_final.h5"
  epitope_valid: "../../data/embeddings/beta/allele/dimension_1024/padded_valid_epitope_embeddings_final.h5"
  tcr_test: "../../data/embeddings/beta/allele/dimension_1024/padded_test_tcr_embeddings_final.h5"
  epitope_test: "../../data/embeddings/beta/allele/dimension_1024/padded_test_epitope_embeddings_final.h5"