epochs: 10
batch_size: 32
learning_rate: 0.001
embed_dim: 128
num_heads: 8
num_layers: 2
max_tcr_length: 43
max_epitope_length: 43
model_path: "results/trained_models/v1_mha.pth"
data_paths:
  train: "../../data/splitted_datasets/allele/beta/train.tsv"
  val: "../../data/splitted_datasets/allele/beta/validation.tsv"
  test: "../../data/splitted_datasets/allele/beta/test.tsv"
embeddings:
  tcr: "../../data/embeddings/beta/allele/TRB_beta_embeddings.npz"
  epitope: "../../data/embeddings/beta/allele/Epitope_beta_embeddings.npz"
