epochs: 10
batch_size: 32
learning_rate: 0.001
embed_dim: 128
num_heads: 8
num_layers: 2
max_tcr_length: 30
max_epitope_length: 30
model_path: "results/trained_models/best_baseline_model.pth"
data_paths:
  train: "data/splitted_datasets/train.csv"
  val: "data/splitted_datasets/val.csv"
  test: "data/splitted_datasets/test.csv"
embeddings:
  tcr: "data/embeddings/tcr_embeddings.pt"
  epitope: "data/embeddings/epitope_embeddings.pt"
