epochs: 10
batch_size: 32
learning_rate: 0.001
embed_dim: 128
num_heads: 8
num_layers: 2
max_tcr_length: 43
max_epitope_length: 43
model_path: "results/trained_models/v1_mha/v1_mha.pth"
data_paths:
  train: "../../data/splitted_datasets/allele/beta/train.tsv"
  val: "../../data/splitted_datasets/allele/beta/validation.tsv"
  test: "../../data/splitted_datasets/allele/beta/test.tsv"
embeddings:
  tcr: "../../data/embeddings/beta/allele/padded/padded_tcr_embeddings_final.h5"
  epitope: "../../data/embeddings/beta/allele/padded/padded_epitope_embeddings_final.h5"
  tcr_train: "../../data/embeddings/beta/allele/padded_pca/tcr_padded_batches_train/"
  epitope_train: "../../data/embeddings/beta/allele/padded_pca/epitope_padded_batches_train/"
  tcr_valid: "../../data/embeddings/beta/allele/padded_pca/valid_tcr_padded_batches/"
  epitope_valid: "../../data/embeddings/beta/allele/padded_pca/valid_epitope_padded_batches/"
  tcr_test: "../../data/embeddings/beta/allele/padded_pca/test_tcr_padded_batches/"
  epitope_test: "../../data/embeddings/beta/allele/padded_pca/test_epitope_padded_batches/"
