epochs: 25
batch_size: 16
<<<<<<< HEAD
learning_rate: 0.004518
=======
learning_rate: 0.0001
>>>>>>> 94654f12c31d780adcda8273b594d94ecb205f52
embed_dim: 128
num_heads: 8
num_layers: 2
max_tcr_length: 43
max_epitope_length: 43
model_path: "results/trained_models/v2_mha/v2_mha.pth"
data_paths:
  train: "../../../../data/splitted_datasets/allele/beta/train.tsv"
  val: "../../../../data/splitted_datasets/allele/beta/validation.tsv"
  test: "../../../../data/splitted_datasets/allele/beta/test.tsv"
embeddings:
  tcr: "../data/embeddings/beta/allele/padded/padded_tcr_embeddings_final.h5"
  epitope: "../data/embeddings/beta/allele/padded/padded_epitope_embeddings_final.h5"
  tcr_train: "../data/embeddings/beta/allele/padded_pca/padded_train_tcr_embeddings_final.h5"
  epitope_train: "../data/embeddings/beta/allele/padded_pca/padded_train_epitope_embeddings_final.h5"
  tcr_valid: "../data/embeddings/beta/allele/padded_pca/padded_valid_tcr_embeddings_final.h5"
  epitope_valid: "../data/embeddings/beta/allele/padded_pca/padded_valid_epitope_embeddings_final.h5"
  tcr_test: "../data/embeddings/beta/allele/padded_pca/padded_test_tcr_embeddings_final.h5"
  epitope_test: "../data/embeddings/beta/allele/padded_pca/padded_test_epitope_embeddings_final.h5"