project: dataset-allele
program: models_scripts/v1_mha/train-server2-bb-v3-pe-ht.py
method: bayes  # oder "random" für schnelleres explorieren, grid search

metric:
  name: val_ap
  goal: maximize

parameters:
  learning_rate:
    min: 0.00005
    max: 0.005
  weight_decay:
    min: 0.00001
    max: 0.001
  batch_size:
    value: 128
  num_layers:
    values: [1, 2]
  num_heads:
    values: [2, 4]
  optimizer:
    values: ["adam"]
  dropout:
    min: 0.1
    max: 0.4
  embed_dim:
    values: [64, 96, 128]
  classifier_hidden_dim:
    values: [32, 64, 128]

